# Generated by Django 3.0.5 on 2020-04-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200422_1837'),
        ('posts', '0003_post_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.Counties'),
        ),
    ]
