# Generated by Django 3.0.5 on 2020-04-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
