# Generated by Django 3.0.5 on 2020-04-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20200419_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counties',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='counties',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='cty_code',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='dis',
        ),
        migrations.AddField(
            model_name='counties',
            name='lcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='luaswh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='namobj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='tipadm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='wadmkc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='wadmkk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='wadmpr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
