# Generated by Django 3.0.5 on 2020-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20200419_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counties',
            name='lcode',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='luaswh',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='namobj',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='shape_leng',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='tipadm',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='wadmkc',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='wadmkk',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='wadmpr',
        ),
        migrations.AddField(
            model_name='counties',
            name='cc_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='engtype_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_0',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_0',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='type_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='varname_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
