# Generated by Django 3.0.5 on 2020-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20200419_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counties',
            name='cc_2',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='engtype_2',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='hasc_2',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='nl_name_1',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='nl_name_2',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='type_2',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='varname_2',
        ),
        migrations.AddField(
            model_name='counties',
            name='cc_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='engtype_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='gid_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_3',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='name_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='type_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='varname_4',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
