# Generated by Django 3.0.5 on 2020-04-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_auto_20200421_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
    ]
