# Generated by Django 3.0.5 on 2020-05-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200422_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='name',
            field=models.TextField(),
        ),
    ]
